version: '3.3'
services:
    golang-service:
        container_name: golang-service
        image: golang-service
        build:
            context: ./golang-service
            dockerfile: Dockerfile
        ports:
        - "8009:8009"
        restart: always 
        networks:
            - monitor-net             
    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./prometheus/:/etc/prometheus/
            - prometheus_data:/prometheus            
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--storage.tsdb.retention=200h'
            - '--web.enable-lifecycle'      
#            - '--alertmanager.url=http://alertmanager:9093'
        restart: unless-stopped
        expose:
            - 9090
        ports:
            - '9090:9090'
        depends_on: 
            - node-exporter
            - golang-service
 #           - alertmanager
        networks:
            - monitor-net
    node-exporter:
        #https://github.com/prometheus/node_exporter
        #https://hub.docker.com/r/prom/node-exporter
        image: prom/node-exporter:latest
        container_name: node-exporter
        user: root
        privileged: true
        volumes:
          - /proc:/host/proc:ro
          - /sys:/host/sys:ro
          - /:/rootfs:ro
        command:
          - '--path.procfs=/host/proc'
          - '--path.sysfs=/host/sys'
          - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
        restart: unless-stopped
        expose:
          - 9100
        networks:
            - monitor-net
#     alertmanager:
#         #https://github.com/prometheus/alertmanager
#         #https://hub.docker.com/r/prom/alertmanager
#         image: prom/alertmanager
#         container_name: alertmanager
#         volumes: 
#             - ./alertmanager/:/etc/alertmanager/
#         command:
# #            - '--config.file=/etc/alertmanager/config-email.yml'
#             - '--storage.path=/alertmanager'
#             - '--web.listen-address=0.0.0.0:9093'
#         restart: unless-stopped
#         ports:
#             - "9093:9093"
#         networks:
#             - monitor-net            
    # pushgateway:
    #     #https://github.com/prometheus/pushgateway
    #     #https://hub.docker.com/r/prom/pushgateway
    #     image: prom/pushgateway:v1.0.1
    #     port:
    #     - 9091:9091
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        volumes:
          - grafana_data:/var/lib/grafana
        #   - ./grafana/datasources:/etc/grafana/datasources
        #   - ./grafana/dashboards:/etc/grafana/dashboards
        #   - ./grafana/setup.sh:/setup.sh
        # entrypoint: /setup.sh
        environment:
          - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
          - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
          - GF_USERS_ALLOW_SIGN_UP=false
        restart: unless-stopped
        expose:
          - 3000
        ports:
          - 3000:3000
        networks:
          - monitor-net
volumes:
    prometheus_data: {}
    grafana_data: {}
networks:
    monitor-net:
        driver: bridge